#!/bin/sh
echo "****************************************"
echo "* CorvoBoys tvAddon Panel installed    *"
echo "*   Please .. Restarting Enigma2       *"
echo "*    by Lululla                        *"
echo "*     all right reserved               *"
echo "*  support on                          *"
echo "*  forum corvoboys or linuxsat-support *"
echo "****************************************"

cmd22='/usr/bin/wget'
cmd23=$(apt-get update && apt-get install wget)
if [ -f $cmd22 ]; then
    echo "wget exist"
else apt-get update && apt-get install wget
fi

wget --no-cache --no-dns-cache --no-check-certificate -U 'Enigma2 - tvaddon Plugin' -c 'http://patbuweb.com/tvPanelxxx/tvaddon.tar' -O /tmp/tvaddon.tar --post-data='action=purge';tar -xvf /tmp/tvaddon.tar -C /

exit 0
