#!/bin/sh
echo "****************************************"
echo "*Please .. Restart Enigma2 *"
echo "****************************************"
echo "* Enjoy our plugin *"
echo "****************************************"
echo "* All Rights Reserved *"
echo "* © 2024 - Lululla *"
echo "****************************************"

cmd22='/usr/bin/wget'
cmd23=$(apt-get update && apt-get install wget)
if [ -f $cmd22 ]; then
    echo "wget exist"
else apt-get update && apt-get install wget
fi

# wget --no-check-certificate --no-cache --no-dns-cache -U 'Enigma2 - tvaddon Plugin' -c 'http://patbuweb.com/tvPanelxxx/tvaddon.tar' -O '/tmp/tvaddon.tar' --post-data='action=purge';tar -xvf /tmp/tvaddon.tar -C /;rm -rf /tmp/tvaddon.tar

exit 0
