#!/bin/sh
echo "Checking for an older version of TiVustream Panel in the system..."
EXTDIR="/usr/lib/enigma2/python/Plugins/Extensions/tvaddon"
if [ -d "$EXTDIR" ]; then
   rm -rf "$EXTDIR" > /dev/null 2>&1
fi

exit 0
